#! /bin/sh

# Halt on error
set -e

# Configure system banners
dpkg-divert --add --package mylinux-iut --rename --divert /etc/issue.net.backup /etc/issue.net
cat /etc/issue.net.backup >> /etc/issue.net.mylinux-iut
ln -sfv /etc/issue.net.mylinux-iut /etc/issue.net

# Disable the CNTLM service
systemctl stop cntlm
systemctl disable cntlm

# Restart the NTP client service
systemctl restart systemd-timesyncd.service
