#! /bin/sh

# Halt on error
set -e

# Remove our configuration
#[ -L /etc/issue ] && ln -sfv /etc/issue.mdebian /etc/issue
#[ -L /etc/issue.net ] && rm -fv /etc/issue.net
#dpkg-divert --remove --package mdebian-iut-base --rename --divert /etc/issue.net.backup /etc/issue.net
