#! /bin/sh

# Install VirtualBox guest additions
#apt install --yes --install-recommends dkms linux-headers-amd64 build-essential
#mount /media/cdrom
#cd /media/cdrom
#sh ./VBoxLinuxAdditions.run

apt install --yes virtualbox-guest-dkms
#apt install --yes virtualbox-guest-x11