#! /bin/sh

# Install Atom
apt install -f -y minicom

# Configure minicom
cat > /etc/minicom/minirc.dfl <<EOF
pu port             /dev/ttyS0
#pu port             /dev/ttyUSB0
pu baudrate         9600
pu bits             8
pu parity           N
pu stopbits         1
pu rtscts           No
pu xonxoff          No
EOF
